# Generated by Django 4.2.11 on 2024-05-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infos',
        ),
    ]
