# Generated by Django 4.2.11 on 2024-05-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
