# Generated by Django 4.2.11 on 2024-05-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
